name: LightCraftHub
main: com.lightcraftmc.hub.main.Main
version: 1.0
description: Hub PLugin
author: mike1665
depend: [LightCraftFusebox]
commands:
    caoff:
    gadgets:
    stats:
    givetokens:
    givecoins:
    addstaff:
    cosmenu:
    parkour:
    setparkour1:
    parkour1:
    mountmenu:
    cp1:
    g-reward:
    sheeplol:
    test:
    rank:
    test:
    delfriend:
    friend:
    setmountspawn:
    unlockmount:
    ammotest:
    gadmenu:
    giveammo:
    sqlban:
    wardrobe:
    colorhelm:
    unlockallarmor:
    arc:
    extrafx: